import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-gray-800 text-gray-100 p-4">
          <nav className="flex space-x-4">
            <Link href="/">Home</Link>
            <Link href="/admin/reps">Admin Reps</Link>
            <Link href="/admin/reps/john">Admin Reps John</Link>
            <Link href="/admin/reps/john/leads">Admin Reps John Leads</Link>
            <Link href="/admin/lead">Admin Lead</Link>
            <Link href="/admin/lead/list">Admin Lead List</Link>
            <Link href="/reps/john">Reps John</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
